/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.practicaguiada8;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class Jf
        extends javax.swing.JFrame {

    /**
     * Creates new form Jf
     */
    public Jf() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jlblCuadros = new javax.swing.JLabel();
        jbtnConfirmar = new javax.swing.JButton();
        jbtnEntradas = new javax.swing.JButton();
        jbtnMensajes = new javax.swing.JButton();
        jbtnOpciones = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlblCuadros.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jlblCuadros.setText("Cuadros de dialogo");

        jbtnConfirmar.setText("Confirmar");
        jbtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnConfirmarActionPerformed(evt);
            }
        });

        jbtnEntradas.setText("Entradas");
        jbtnEntradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEntradasActionPerformed(evt);
            }
        });

        jbtnMensajes.setText("Mensajes");
        jbtnMensajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMensajesActionPerformed(evt);
            }
        });

        jbtnOpciones.setText("Opciones");
        jbtnOpciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnOpcionesActionPerformed(evt);
            }
        });

        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jlblCuadros)
                .addContainerGap(151, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtnConfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnEntradas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnMensajes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnOpciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jlblCuadros)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtnConfirmar)
                        .addGap(29, 29, 29)
                        .addComponent(jbtnEntradas)
                        .addGap(35, 35, 35)
                        .addComponent(jbtnMensajes)
                        .addGap(27, 27, 27)
                        .addComponent(jbtnOpciones))
                    .addComponent(jScrollPane1))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnConfirmarActionPerformed
       int valor;
       txtArea.setText("");
       valor = JOptionPane.showConfirmDialog(this, "¿Confirmas movimiento?");
       txtArea.setText("Resupeusta de movimiento: "+valor);
       valor = JOptionPane.showConfirmDialog(this, "¿Borrar dato?", "Eliminar informacion", JOptionPane.OK_CANCEL_OPTION);
       txtArea.setText(txtArea.getText() + "\nRepuesta borrar: " + valor);  
       valor = JOptionPane.showConfirmDialog(this, "Autoriza el cambio", "Confirmacion", JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);
       txtArea.setText(txtArea.getText() + "\nRespuesta de cambio: " + valor);
       ImageIcon icono = new ImageIcon("C:/Users/Usuario/Desktop/TMP ALUMNOS/PracticaGuiada8/src/main/java/com/mycompany/practicaguiada8/casa.png");
       valor = JOptionPane.showConfirmDialog(this, "Autoriza transferencia", "Confirmacion", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE, icono);
       txtArea.setText(txtArea.getText() + "\nRespuesta a transferencia: " + valor);
    }//GEN-LAST:event_jbtnConfirmarActionPerformed

    private void jbtnEntradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEntradasActionPerformed
       String respuesta;
       int edad;
       txtArea.setText("");
       
       respuesta = JOptionPane.showInputDialog("Ingresa nombre:");
       txtArea.setText("Nombre: " + respuesta + "\n");
       ////////////////////////////////////////////////////////////////////////////////////////
       respuesta = JOptionPane.showInputDialog(this, "Ingresa edad: ");
       edad = Integer.parseInt(respuesta);
       txtArea.append("Edad: " + edad + "\n");
       ////////////////////////////////////////////////
       respuesta = JOptionPane.showInputDialog(this, "Apellido materno", "Hernandez");
       txtArea.append("Materno: " + respuesta + "\n");
    }//GEN-LAST:event_jbtnEntradasActionPerformed

    private void jbtnMensajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMensajesActionPerformed
       txtArea.setText("");
       ImageIcon icono = new ImageIcon("C:/Users/Usuario/Desktop/TMP ALUMNOS/PracticaGuiada8/src/main/java/com/mycompany/practicaguiada8/casa.png");
       JOptionPane.showMessageDialog(null, "Datos capturados");
       JOptionPane.showMessageDialog(this, "Esta es una advertencia", "Informativo", JOptionPane.WARNING_MESSAGE);
       JOptionPane.showMessageDialog(this, "Credita de vivienda aprobado", "Vivienda", JOptionPane.PLAIN_MESSAGE, icono);
    }//GEN-LAST:event_jbtnMensajesActionPerformed

    private void jbtnOpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnOpcionesActionPerformed
        txtArea.setText("");
        String opciones[] = {"Alfa", "Beta", "Gama", "Epsilon", "Etha", "Otra"};
        ImageIcon icono = new ImageIcon("C:/Users/Usuario/Desktop/TMP ALUMNOS/PracticaGuiada8/src/main/java/com/mycompany/practicaguiada8/casa.png");
        int respuesta;
        respuesta = JOptionPane.showOptionDialog(this,"Elige una de las letras: ", "Letras griegas", JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE, icono, opciones, opciones[0]);
        txtArea.append("Opcion numerica: " + respuesta + "\n" + "Opcion textual: " + opciones[respuesta]);
    }//GEN-LAST:event_jbtnOpcionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.
                    getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jf.class.getName()).
                    log(java.util.logging.Level.SEVERE,
                            null,
                            ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jf.class.getName()).
                    log(java.util.logging.Level.SEVERE,
                            null,
                            ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jf.class.getName()).
                    log(java.util.logging.Level.SEVERE,
                            null,
                            ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jf.class.getName()).
                    log(java.util.logging.Level.SEVERE,
                            null,
                            ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jf().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jbtnConfirmar;
    private javax.swing.JButton jbtnEntradas;
    private javax.swing.JButton jbtnMensajes;
    private javax.swing.JButton jbtnOpciones;
    private javax.swing.JLabel jlblCuadros;
    private javax.swing.JTextArea txtArea;
    // End of variables declaration//GEN-END:variables
}
